OPENAI_API_KEY = "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"
ELEVENLABS_API_KEY = "sk_dd4364dc38686fad66678f103974a1266ed0dfaeb6051654"
